# Default values for v1-orgs-transformer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 1
image:
  repository: coco/v1-orgs-transformer
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 1536Mi
cache:
  size: 5Gi
  nfsServer: ""
  path: "/"
env:
  PORT: 8080
  BASE_URL: "http://v1-orgs-transformer:8080/transformers/organisations/"
  CACHE_FILE_NAME: "/cache/v1-orgs-transformer.db"
  LOG_METRICS: false
