# Values used for the deployed application.
replicaCount: 1
service:
  name: v1-orgs-transformer
cache:
  size: 5Gi
  nfsServer: fs-6330fcaa.efs.eu-west-1.amazonaws.com
  path: "/"
env:
  PORT: 8080
  BASE_URL: "http://v1-orgs-transformer:8080/transformers/organisations/"
  CACHE_FILE_NAME: "/cache/v1-orgs-transformer.db"
  LOG_METRICS: false